version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    container_name: ${DOCKER_CONTAINER_NAME}_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - devituz
    environment:
      APP_ENV: local
      WWWUSER: '${WWWUSER:-1000}'
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - pgsql
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: ${DOCKER_CONTAINER_NAME}_nginx
    ports:
      - '${APP_PORT:-8010}:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - devituz
    restart: unless-stopped


  pgsql:
    image: postgres:17
    container_name: ${DOCKER_CONTAINER_NAME}_pgsql
    ports:
      - '${FORWARD_DB_PORT:-5434}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    networks:
      - devituz
    restart: unless-stopped


  migration:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    container_name: ${DOCKER_CONTAINER_NAME}_migration
    command: bash -c "php yii migrate --interactive=0"
    depends_on:
      - app
      - pgsql
    networks:
      - devituz
    environment:
      APP_ENV: local
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - .:/var/www/html
    restart: unless-stopped

volumes:
  pgsql-data:

networks:
  devituz:
    driver: bridge
